package org.bytecub.reconsilationx.aUsrMgt.constants;

public class EmailTemplates {

    public static final String USER_CREATION_EMAIL_SUBJECT = "👋 Welcome to {{companyName}} on ProjeXpert! Activate Your Account";

    public static final String USER_CREATION_EMAIL_CONTENT = "<!DOCTYPE html>"
            + "<html>"
            + "<head>"
            + "<style>"
            + "  body { font-family: Arial, sans-serif; color: #333333; }"
            + "  .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }"
            + "  .header { text-align: center; padding-bottom: 20px; }"
            + "  .content { background-color: #ffffff; padding: 20px; border-radius: 8px; }"
            + "  .footer { font-size: 12px; text-align: center; color: #777777; padding-top: 20px; }"
            + "  h1 { color: #3C8F53; }"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "  <div class='header'>"
            + "    <h1>Welcome to {{companyName}}, {{firstName}}! 🚀</h1>"
            + "  </div>"
            + "  <div class='content'>"
            + "    <p>Your account for {{companyName}} on ProjeXpert has been created! You're now one step closer to smarter project management and team collaboration.</p>"
            + "    <hr>"
            + "    <p><strong>Your Profile Details:</strong><br>"
            + "       Username: <strong>{{username}}</strong><br>"
            + "       User ID: <strong>{{userId}}</strong></p>"
            + "    <hr>"
            + "    <h2>Activate Your Account</h2>"
            + "    <p>Click below to verify and get started:</p>"
            + "    <p><a href='{{verificationLink}}' style='color: #3C8F53; font-weight: bold;'>Activate My Account</a></p>"
            + "    <p>If the button doesn't work, copy and paste this link into your browser:<br>{{verificationLink}}</p>"
            + "    <hr>"
            + "    <h2>With ProjeXpert You Can:</h2>"
            + "    <ul>"
            + "      <li>Create and manage your projects and tasks</li>"
            + "      <li>Track deadlines, attendance, and performance</li>"
            + "      <li>Collaborate with your {{companyName}} team in real time</li>"
            + "    </ul>"
            + "    <p>Let’s get productive together! 💼</p>"
            + "  </div>"
            + "  <div class='footer'>"
            + "    <p>Need help? Contact <a href='mailto:support@projexpert.app'>support@reconsilationx.app</a></p>"
            + "  </div>"
            + "</div>"
            + "</body>"
            + "</html>";

    public static final String EXPIRED_LINK_EMAIL_SUBJECT = "⏳ Your {{companyName}} ProjeXpert Verification Link Expired";

    public static final String EXPIRED_LINK_EMAIL_CONTENT = "<!DOCTYPE html>"
            + "<html>"
            + "<head>"
            + "<style>"
            + "  body { font-family: Arial, sans-serif; color: #333333; }"
            + "  .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }"
            + "  .header { text-align: center; padding-bottom: 20px; }"
            + "  .content { background-color: #ffffff; padding: 20px; border-radius: 8px; }"
            + "  .footer { font-size: 12px; text-align: center; color: #777777; padding-top: 20px; }"
            + "  h1 { color: #FF9800; }"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "  <div class='header'>"
            + "    <h1>Your {{companyName}} Verification Link Has Expired</h1>"
            + "  </div>"
            + "  <div class='content'>"
            + "    <p>No worries, {{firstName}}. Here's a fresh link to activate your {{companyName}} account on ProjeXpert:</p>"
            + "    <p><a href='{{newVerificationLink}}' style='color: #FF9800; font-weight: bold;'>Click to Verify</a></p>"
            + "    <p>Or copy and paste this link into your browser:<br>{{newVerificationLink}}</p>"
            + "  </div>"
            + "  <div class='footer'>"
            + "    <p>{{companyName}} – Powered by ProjeXpert</p>"
            + "  </div>"
            + "</div>"
            + "</body>"
            + "</html>";

    public static final String PASSWORD_RESET_EMAIL_SUBJECT = "🔐 Reset Your {{companyName}} ProjeXpert Password";

    public static final String PASSWORD_RESET_EMAIL_CONTENT = "<!DOCTYPE html>"
            + "<html>"
            + "<head>"
            + "<style>"
            + "  body { font-family: Arial, sans-serif; color: #333333; }"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "  <div class='header'>"
            + "    <h1>Reset Your Password</h1>"
            + "  </div>"
            + "  <div class='content'>"
            + "    <p>Use the following OTP to reset your {{companyName}} account password on ProjeXpert:</p>"
            + "    <h2 style='color: #3C8F53; font-size: 2em;'>{{otp}}</h2>"
            + "    <p>This OTP is valid for 10 minutes. If you didn’t request this, please secure your account.</p>"
            + "  </div>"
            + "</div>"
            + "</body>"
            + "</html>";

    public static final String PASSWORD_RESET_SUCCESS_EMAIL_SUBJECT = "✅ {{companyName}} Password Updated on ProjeXpert";

    public static final String PASSWORD_RESET_SUCCESS_EMAIL_CONTENT = "<!DOCTYPE html>"
            + "<html>"
            + "<head>"
            + "<style>"
            + "  body { font-family: Arial, sans-serif; color: #333333; }"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "  <div class='header'>"
            + "    <h1>Password Reset Successful</h1>"
            + "  </div>"
            + "  <div class='content'>"
            + "    <p>Hello {{firstName}},</p>"
            + "    <p>Your {{companyName}} account password has been updated. You can now:</p>"
            + "    <ul>"
            + "      <li>Access projects and dashboards</li>"
            + "      <li>Manage tasks with your {{companyName}} team</li>"
            + "      <li>Collaborate with full control and clarity</li>"
            + "    </ul>"
            + "    <p>Let’s continue building success! 🔧</p>"
            + "  </div>"
            + "</div>"
            + "</body>"
            + "</html>";

    public static final String CHANGE_PASSWORD_SUCCESS_EMAIL_SUBJECT = "🔒 Password Changed for {{companyName}} on ProjeXpert";

    public static final String CHANGE_PASSWORD_SUCCESS_EMAIL_CONTENT = "<!DOCTYPE html>"
            + "<html>"
            + "<head>"
            + "<style>"
            + "  body { font-family: Arial, sans-serif; color: #333333; }"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "  <div class='header'>"
            + "    <h1>Password Changed Successfully</h1>"
            + "  </div>"
            + "  <div class='content'>"
            + "    <p>Hi {{firstName}},</p>"
            + "    <p>Your password for {{companyName}} on ProjeXpert has been changed. You're all set to continue your work securely.</p>"
            + "  </div>"
            + "</div>"
            + "</body>"
            + "</html>";
}
